doctrine:
    dbal:
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        default_connection: default
        connections:
            default: ~
            #     url: '%env(resolve:DATABASE_URL)%'
            #     charset: UTF-8
            # seguridad:
            #     url: '%env(resolve:DATABASE_URL_SEGURIDAD)%'
            #     charset: UTF-8
    orm:
        # auto_generate_proxy_classes: true
        # naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        # auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default: ~
            #     connection: default
            #     mappings:
            #         Main:
            #             is_bundle: false
            #             type: annotation
            #             dir: '%kernel.project_dir%/src/Entity/Main'
            #             prefix: 'App\Entity\Main'
            #             alias: Main
            # seguridad:
            #     connection: seguridad
            #     mappings:
            #         Seguridad:
            #             is_bundle: false
            #             type: annotation
            #             dir: '%kernel.project_dir%/src/Entity/Seguridad'
            #             prefix: 'App\Entity\Seguridad'
            #             alias: Seguridad
